spring.datasource.url=jdbc:postgresql:///dungeonmapster_test?cloudSqlInstance=${CLOUD_SQL_INSTANCE}&socketFactory=com.google.cloud.sql.postgres.SocketFactory
app.frontend-url=https://dungeon-mapster-test-675207457500.us-central1.run.app
